declare module '*.module.css';
declare module '*.module.scss';
declare module '*.svg';
declare module '*.png';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.woff';
declare module '*.woff2';
declare const __IS_DEV__: boolean;
declare const __API__: string;
